improvement: rework the round creation system
Tran-Antoine/sphinx pull request #48
Opened 2021-02-07 16:36 UTC by firestar24

2021-02-07 17:18 UTC, mredstone6 requested changes

2021-02-07 18:34 UTC, Tran-Antoine commented
I will probably make a PR as a review

2021-02-23 21:20 UTC, Tran-Antoine approved these changes
Thanks for this huge contribution! Good to merge know

2021-02-23 21:26 UTC, mredstone6 approved these changes

2021-02-23 21:28 UTC, merged