security fix
Tran-Antoine/sphinx pull request #57
Opened 2021-02-26 16:05 UTC by mredstone6

# Feature:
- add limit to file upload
- add limit to lobby

2021-02-26 16:14 UTC, Tran-Antoine commented
I'm not a huge fan of the DiscordContext being passed as context parameter

2021-02-27 00:54 UTC, Tran-Antoine requested changes
In every command in which you use the CounterLimiter, I think it would be much better to include its usage in the  `StopConditions.shouldStop` system

2021-02-27 14:19 UTC, Tran-Antoine commented
This also contains a memory leak fix.

2021-02-27 14:22 UTC, mredstone6 commented on discord-impl/src/main/java/net/starype/quiz/discordimpl/command/StartGameCommand.java
> +                "Error: Cannot create a new game as the maximum number of game as been reached");
```suggestion
                "Error: Cannot create a new game as the maximum number of game has been reached");

```

2021-02-27 14:22 UTC, mredstone6 commented on discord-impl/src/main/java/net/starype/quiz/discordimpl/command/CreateLobbyCommand.java
> +               "max lobby limit has been reached");
```suggestion
               "Error: Cannot create new lobby as the maximum number of lobbies has been reached");

```

2021-02-27 16:06 UTC, firestar24 commented on discord-impl/src/main/java/net/starype/quiz/discordimpl/util/InputUtils.java
> +                channel.sendMessage("Error: The limit of downloading zip as been reached").queue();
```suggestion
                channel.sendMessage("Error: The limit of downloading zip has been reached").queue();

```

2021-02-28 15:20 UTC, Tran-Antoine approved these changes

2021-02-28 15:24 UTC, merged